version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api-jwt:
    image: docker.io/library/api-jwt 
    depends_on: 
      - "app_db"
    container_name: api-jwt-services-2
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=containers-us-west-147.railway.app;Port=7133;Database=rest-api-jwt-dotnet;User Id=postgres;Password=HiSyZIssQm1CsmSVT50I;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rest-api-jwt-dotnet
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks: 
      - dev
  
volumes:
   app_data: