version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api-jwt:
    image: docker.io/library/api-jwt 
    container_name: api-jwt-services-2
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=containers-us-west-170.railway.app;Port=7238;Database=railway;User Id=postgres;Password=4hy0c6GlKj3YGa71tZ0i;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
      
volumes:
   app_data: